export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST';
export const CART_PRODUCT_SUCCESS = 'CART_PRODUCT_SUCCESS';
export const CART_PRODUCT_FAIL = 'CART_PRODUCT_FAIL';

export const ADD_CART_PRODUCT_REQUEST = 'ADD_CART_PRODUCT_REQUEST';
export const ADD_CART_PRODUCT_SUCCESS = 'ADD_CART_PRODUCT_SUCCESS';
export const ADD_CART_PRODUCT_FAIL = 'ADD_CART_PRODUCT_FAIL';

export const DELETE_CART_PRODUCT_REQUEST = 'DELETE_CART_PRODUCT_REQUEST';
export const DELETE_CART_PRODUCT_SUCCESS = 'DELETE_CART_PRODUCT_SUCCESS';
export const DELETE_CART_PRODUCT_FAIL = 'DELETE_CART_PRODUCT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';